provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  amp-fairshare:
    lang: python
    handler: ./amp-fairshare
    image: joaopluigi/amp-fairshare:latest
    environment:
      content_type: text/html
  pi-logs:
    lang: python
    handler: ./pi-logs
    image: joaopluigi/pi-logs:latest
