provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  helloworld:
    lang: python3
    handler: ./helloworld
    image: joaopluigi/helloworld:latest
  helloworld2:
    lang: python
    handler: ./helloworld2
    image: joaopluigi/helloworld2:latest
